### ISSUE TITLE
Add some icons for quick action

### ISSUE THREAD

**Issue by irisgyq** [beijinglug/lets-chat#10]
There are three icons next to the room name, like this:
![2015-05-31 12 43 11](https://cloud.githubusercontent.com/assets/8121488/7898321/fcd4df14-072e-11e5-8ce3-91514d8d5e27.png)

One is for editing room, one is for chat record, and another one is for uploading files.

So we can add more icons for quick action, which can be easier.

The first one can be OTR messaging.

**Comment by fallacy321** [comment]
https://github.com/beijinglug/lets-chat/commit/f19a99827d81536ccfb698478d0e9f28daef0b6d

**Comment by tonghuix** [comment]
It seems already been resolved, how about we close it? Do you agree ?

**Comment by fallacy321** [comment]
@irisgyq what do you think?

**Comment by tonghuix** [comment]
![2015-05-31 18 15 57](https://cloud.githubusercontent.com/assets/423703/7901559/1c0b84b8-07c1-11e5-9d58-41f6957dcc8b.png)

It needs a little artwork. at lease same for other icon

**Comment by fallacy321** [comment]
Yes, an icon change could be done easily here I guess :) Also, have I not pushed the code yet? As here it displays like this : 
![mention11](https://cloud.githubusercontent.com/assets/3140219/7906977/e1cf3f7a-0850-11e5-9426-aef5e8ee53f1.png)

**Comment by tonghuix** [comment]
Yup, I saw it.   
Well, still needs some artworks, but no a major issues

**Comment by tonghuix** [comment]
It seems Iris already finished at https://github.com/beijinglug/lets-chat/commit/11b6fc5b20cb05fa9041ed8d407f8c20d963922e, So I prefer close it.
