### ISSUE TITLE
Display the timestamp in transcript as per locale timing

### ISSUE THREAD

**Issue by fallacy321** [beijinglug/lets-chat#12]
At present the timezone displays the time in format ddd, MMM Do YYYY, h:mm:ss . It would be nice to put it in locale settings

**Comment by fallacy321** [comment]
This should help https://github.com/beijinglug/lets-chat/commit/6ed2ff992e4cf8b5f8d62ba05de0a7efd0b70e07

**Comment by tonghuix** [comment]
I prefer close this issue, cause already resolves.
