### ISSUE TITLE
Front-end design for group chat encryption

### ISSUE THREAD

**Issue by tonghuix** [beijinglug/lets-chat#13]
By reviewing code, I discover several lines are duplicated for a feature, such us Key Generation, even only several lines. 

However, it means we need a discussion for UI cooperation so that make every one works perfectly.  I prefer we just talk here.

It is better @irisgyq upload your UI mockup design now.  Just graphs file is OK.

**Comment by irisgyq** [comment]
![group c](https://cloud.githubusercontent.com/assets/8121488/7905854/b5b5c2f4-0852-11e5-846a-447210f9fad4.png)
![group chat otr](https://cloud.githubusercontent.com/assets/8121488/7905857/bc750668-0852-11e5-863d-b02bd4baf01d.png)

**Comment by irisgyq** [comment]
@tonghuix @fallacy321 These are my UI mockup for group chat OTR encryption.

**Comment by tonghuix** [comment]
I don't think timer is necessary. 

For reference, here is the cryptocat's UI, it shows the status at the room title bar, encrypted or not.  
![2015-06-02 01 39 45](https://cloud.githubusercontent.com/assets/423703/7919279/cfe72e5c-08c9-11e5-8b36-9ca8e200b8ec.png)

And a chatter info, it shows room's fingerprint and chatter's. 
![2015-06-02 01 40 02](https://cloud.githubusercontent.com/assets/423703/7919300/fbb13e6a-08c9-11e5-8a19-158f0a1f825c.png)
