### ISSUE TITLE
Merge sdelements/lets-chat 0.4.0

### ISSUE THREAD

**Issue by tonghuix** [beijinglug/lets-chat#14]
sdelements/lets-chat just release 0.4.0, it include a lot of changes.  https://github.com/sdelements/lets-chat/blob/master/CHANGELOG.md

By review this changes, so may effect to us, so anyone who volunteered to merge it to our master?

**Note: A lot of conflicts may facing to....**

**Comment by tonghuix** [comment]
I already finished in my personal repo https://github.com/tonghuix/lets-chat/

Needs someone help to review it.

And running app at https://tonghuixchat.herokuapp.com

**Comment by tonghuix** [comment]
@irisgyq we need update room's UI design, cause when private password protected room is enabled a 'fa-lock' icon will shown on the same place where we designed for our encrypted room....

![2015-06-05 07 37 08](https://cloud.githubusercontent.com/assets/423703/7996700/f100c484-0b55-11e5-9574-029536ba038d.png)

**Comment by tonghuix** [comment]
HAHA, I found a perfect icon that is fa-user-secret https://fortawesome.github.io/Font-Awesome/icon/user-secret/

**Comment by fallacy321** [comment]
@tonghuix @irisgyq is the issue resolved or still pending? :)

**Comment by tonghuix** [comment]
Still it seems I mergeing is fail..

**Comment by tonghuix** [comment]
Done, all merged. 

Please check it and merge to your own branch.
