### ISSUE TITLE
add some more quotes for raptorize plugin

### ISSUE THREAD

**Issue by fallacy321** [beijinglug/lets-chat#16]
When I type "shoot her ! shoot her !" or "clever girl" , a dinosaur appears, which is quite interesting . I would be glad if we can have more of these quotes in blug chat

**Comment by fallacy321** [comment]
@tonghuix should I add some more or we should close this one? I tested the commit earlier it worked well.

**Comment by tonghuix** [comment]
I tested too, so I suggest we could close it.
