### ISSUE TITLE
Make the key entrance more easy to discover

### ISSUE THREAD

**Issue by irisgyq** [beijinglug/lets-chat#20]
Today, @tonghuix ask me about the front-end of key function, I realize that maybe you may not know I have already leave the entrance for it.

![2015-06-20 9 30 13](https://cloud.githubusercontent.com/assets/8121488/8267422/9d2f9778-1793-11e5-9962-166d197b2ad3.png)
![2015-06-20 9 30 29](https://cloud.githubusercontent.com/assets/8121488/8267423/a3e0e04a-1793-11e5-8141-3c2c3773fe99.png)

In the second entrance, there are two ways I think to show the key.
1.Press the button, an alert show up, and the key will show up in a textarea.
2.Press the button, key will show up, press it again and the key will disappear.

We can choose one.

And our goal is simplifying the interaction and let people discover our functions. I will do some improvements to adapt to the users' habits.

**Comment by tonghuix** [comment]
Awesome! So the next thing is show the key up in the web page. 

Note: please show the fingerprint in 8 digital format. Ex: `C1AE87BF 37F40BF7 5A3BFA63 B549217E 4127F631`

**Comment by fallacy321** [comment]
@tonghuix @irisgyq  8 digit format is already pushed just now in Issue #8 so we could perhaps use that ? :+1:

**Comment by tonghuix** [comment]
Yes, @irisgyq could use your strings directly or show follow her willing.
