### ISSUE TITLE
The flow of group chat encryption

### ISSUE THREAD

**Issue by irisgyq** [beijinglug/lets-chat#21]
I looked through the project and found @fallacy321 has already implemented the cryptocat, then the next work is to confirm the flow for encryption.

My idea is:

1. Generate the private key and public key for everyone when he or she **signs up**. The private key is reserved in the client.
2. He/She can see his/her key fingerprint in the window.(issue #20 ) 
3. When one enters into a room, if he/she wants to encrypt the group chat, they must send public keys with each other.
4. One can see another person's fingerprint by pressing this icon next to the person, like this:
![2015-06-22 1 02 34](https://cloud.githubusercontent.com/assets/8121488/8272563/6524eb02-187a-11e5-9ce2-cae72adab9e1.png)
5. Use private key to encrypt before send messages.

**Comment by fallacy321** [comment]
For point 1, I think private and public keys are already generated in Issue #8 ,  so it would be great if the focus is on how to display it at the front -end from terminal :) 
Same goes for point 2. 
For point 3 and 4, issue #15 would help you, I have already tried AES encryption and Hash algorithm there. So why a new mechanism for that? We can just make it more efficient and move it to front-end . 
@irisgyq @tonghuix  let me know if I am going wrong :)

**Comment by tonghuix** [comment]
Here is cryptocat did for your reference:
https://github.com/cryptocat/cryptocat/wiki/Multiparty-Protocol-Specification

````
Each user's privateKey is stored within her/his Cryptocat client and is never shared. The user's publicKey is then generated:

// Generate public key (Curve 25519 Diffie-Hellman with basePoint 9) myPublicKey = Curve25519.ecDH(myPrivateKey);

A user A may her/his public key to B using a JSON object formatted as follows:

{"type":"publicKey", nickA:{"message":publicKeyB}} where publicKeyB is encoded using Base64.

Once a user receives another user's public key, s/he must send her/his own public key in return. Thus, user A requests user B's public key merely by sending her/his own public key.

Alternately, a plain public key request can be made by sending the following message:

{"type":"publicKeyRequest", nickA:{}}

Both key request and reply messages are not encrypted and do not include an HMAC or tag.

Note: If a client receives a public key from another user and they already have a public key on record for them, the new public key is not accepted. In other words, only one key agreement per user per conversation is allowed.
````

**Comment by irisgyq** [comment]
I want to know whether we need to show the private key in the front-end window?

I think we only need to show the user's fingerprint and other users' fingerprints to certificate others. And the encryption is finished in the server end, there is no key found in the front-end window. Do I have a wrong understanding?

**Comment by tonghuix** [comment]
@irisgyq You are correct. Only show the fingerprint is OK. Console print which @fallacy321 did before just for our code and testing usage.

**Comment by irisgyq** [comment]
I see, thanks~
