### ISSUE TITLE
Key generation for group OTR chat

### ISSUE THREAD

**Issue by tonghuix** [beijinglug/lets-chat#8]

**Comment by fallacy321** [comment]
https://github.com/fallacy321/lets-chat/commit/d3f584f7dbcab02d6c61162f67ff1d7a5f1cbc37

**Comment by fallacy321** [comment]
![mention12](https://cloud.githubusercontent.com/assets/3140219/7907085/43e1a45e-0852-11e5-8876-a9d58eb4d451.png)

**Comment by fallacy321** [comment]
Increased the range 
![mention13](https://cloud.githubusercontent.com/assets/3140219/7907168/a76f4638-0853-11e5-8078-89d8207bed0a.png)

**Comment by fallacy321** [comment]
![mention14](https://cloud.githubusercontent.com/assets/3140219/7979285/905c807c-0abb-11e5-9705-ee8c2d399f9c.png)

**Comment by fallacy321** [comment]
https://github.com/beijinglug/lets-chat/commit/f38add2fe4b06d9e9b704ed45794ed1f7039e423

**Comment by fallacy321** [comment]
Please do npm install crypto-js

**Comment by fallacy321** [comment]
![mention15](https://cloud.githubusercontent.com/assets/3140219/7979955/62079e5e-0ac1-11e5-825d-fabcd45b7f70.png)

**Comment by tonghuix** [comment]
Good Job!
But a little confuse by reviewing the code. what is the bits length of the key? And base64 string is the key fingerprint, which is hashed string for the key, or just a key string's base64.

**Comment by fallacy321** [comment]
![mention16](https://cloud.githubusercontent.com/assets/3140219/7990301/cbdc3bfe-0b0d-11e5-8f6d-43c359b77303.png)

**Comment by tonghuix** [comment]
I tested it with 2048bits and 4096bits. It seems they all works. but 2048 needs more than 50 sec to generate a key.  And 4096 needs more than 4 mins to generate a key. so that it is better give user a notice or a progress for the waiting time.

I just curious why cryptocat generate a key so fast....only because they use ECC?

## 2048
![2015-06-05 01-58-55](https://cloud.githubusercontent.com/assets/423703/7991554/91496fb6-0b2b-11e5-832c-fcf4f5d354d0.png)

## 4096
![2015-06-05 02-34-09](https://cloud.githubusercontent.com/assets/423703/7991596/f0709140-0b2b-11e5-9a80-1fc6b58295d0.png)

**Comment by fallacy321** [comment]
![mention17](https://cloud.githubusercontent.com/assets/3140219/8011645/eb5aea5a-0bd7-11e5-8dba-b5f778111468.png)

**Comment by fallacy321** [comment]
![mention19](https://cloud.githubusercontent.com/assets/3140219/8134279/7b3fa99e-114b-11e5-883a-5c459fb309d9.png)

**Comment by tonghuix** [comment]
Please print fingerprint of the key. Thay require use SHA-1 or SHA-256 to hash the key. and print as 8 digital hex  format
''''
1234ABCD 1234ABCD 1234ABCD
''''

**Comment by fallacy321** [comment]
![fingerprint](https://cloud.githubusercontent.com/assets/3140219/8177934/27806ba2-1427-11e5-90fa-dd088bf58380.png)

**Comment by fallacy321** [comment]
@tonghuix do I need to use split() on the hash value generated for fingerprint? If so, what should be the condition to split as it is randomly mixed letters and digits

**Comment by tonghuix** [comment]
well, I think we should print it on front-end, however, if it not bothering you, please split it.

**Comment by fallacy321** [comment]
I think that is what @irisgyq has to do , she has to figure out a way to print key in front end. we can then easily print this as well .

**Comment by tonghuix** [comment]
I mean you could print and split it in console. It would help you code and test it.

**Comment by fallacy321** [comment]
![split1](https://cloud.githubusercontent.com/assets/3140219/8267363/cd92fe54-177b-11e5-8c22-3bb6e8fee4e2.png)

**Comment by fallacy321** [comment]
![split2](https://cloud.githubusercontent.com/assets/3140219/8267638/aa88b41a-1787-11e5-96e5-989dc1ec7fcb.png)

**Comment by tonghuix** [comment]
Well Done ! Excellent !

I would close this issue.
