### ISSUE TITLE
Add a menu for group encryption chat

### ISSUE THREAD

**Issue by tonghuix** [beijinglug/lets-chat#9]
It is better adding a menu for a group chat. 

And thanks to @fallacy321 's contribution, so that we could just modify her file directly.

**Comment by tonghuix** [comment]
I suppose we could add this menu just near group file upload window.

**Comment by fallacy321** [comment]
This should help to proceed 

https://github.com/beijinglug/lets-chat/commit/0cd40b548971b969a4327d4c0fe2752848356345

**Comment by tonghuix** [comment]
@fallacy321 well done!
@irisgyq may work follow exist interface

**Comment by tonghuix** [comment]
The sidebar messed up...
![2015-05-29 21 00 21](https://cloud.githubusercontent.com/assets/423703/7883469/5315c80c-0649-11e5-9eab-7418debf5a4b.png)

**Comment by tonghuix** [comment]
It seems @irisgyq already fix it. Nice!

**Comment by fallacy321** [comment]
I was just going through the code and found that herf is there in the code instead of href 
https://github.com/beijinglug/lets-chat/commit/a370fc3b6dc61f63b178c705b462bf98b90ca174

**Comment by irisgyq** [comment]
That's right!! Thank you~~

2015-05-31 4:09 GMT+08:00 Heena Mahour <notifications@github.com>:

**Comment by fallacy321** [comment]
does clicking OTR provides a new window? If so, It is not getting displayed here though :( @irisgyq ?

**Comment by irisgyq** [comment]
@fallacy321 Yeah, it provides a new window.
